import { MenuConfig } from '@/types/menu';

/** 按业务域分组，减少一级菜单数量；子项权限不变 */
export const menuConfig: MenuConfig = {
  items: [
    {
      id: 'chat-consultant',
      label: '智能沟通',
      path: '/chat',
      icon: 'chat-icon',
      roles: ['customer', 'admin', 'operator'],
      priority: 100,
    },
    {
      id: 'task-group',
      label: '任务',
      path: '/tasks',
      icon: 'task-icon',
      roles: ['customer', 'admin', 'operator'],
      priority: 90,
      children: [
        {
          id: 'tasks-admin',
          label: '任务管理',
          path: '/tasks',
          icon: 'task-icon',
          roles: ['customer', 'admin', 'operator'],
        },
        {
          id: 'task-governance-admin',
          label: '任务治理',
          path: '/admin/task-governance',
          icon: 'governance-icon',
          roles: ['admin'],
        },
      ],
    },
    {
      id: 'contacts',
      label: '通讯录',
      path: '/contacts',
      icon: 'contacts-icon',
      roles: ['doctor', 'consultant', 'customer', 'admin', 'operator'],
      priority: 80,
    },
    {
      id: 'datahub-group',
      label: 'DataHub',
      path: '/admin/datahub',
      icon: 'stats-icon',
      roles: ['admin'],
      priority: 70,
      children: [
        {
          id: 'datahub-daily-brief',
          label: '每日看盘',
          path: '/admin/datahub',
          icon: 'stats-icon',
          roles: ['admin'],
        },
        {
          id: 'datahub-watchlist',
          label: '自选股',
          path: '/admin/datahub/watchlist',
          icon: 'stats-icon',
          roles: ['admin'],
        },
        {
          id: 'datahub-acquisition',
          label: '数据获取（高级）',
          path: '/admin/datahub/acquisition',
          icon: 'stats-icon',
          roles: ['admin'],
        },
        {
          id: 'datahub-monitor',
          label: '运行监控',
          path: '/admin/datahub/monitor',
          icon: 'stats-icon',
          roles: ['admin'],
        },
      ],
    },
    {
      id: 'ai-capabilities-group',
      label: 'AI 能力',
      path: '/admin/digital-humans',
      icon: 'agent-icon',
      roles: ['admin'],
      priority: 60,
      children: [
        {
          id: 'digital-humans-admin',
          label: '数字人管理',
          path: '/admin/digital-humans',
          icon: 'digital-human-icon',
          roles: ['admin'],
        },
        {
          id: 'agents-setup',
          label: '智能体配置',
          path: '/agents/setup',
          icon: 'agent-icon',
          roles: ['admin'],
        },
        {
          id: 'agents-knowledge',
          label: '知识库管理',
          path: '/agents/knowledge',
          icon: 'records-icon',
          roles: ['admin'],
        },
        {
          id: 'mcp',
          label: 'MCP 配置',
          path: '/mcp',
          icon: 'mcp-icon',
          roles: ['admin'],
        },
      ],
    },
    {
      id: 'system-admin-group',
      label: '系统管理',
      path: '/users',
      icon: 'users-icon',
      roles: ['admin'],
      priority: 50,
      children: [
        {
          id: 'users',
          label: '用户管理',
          path: '/users',
          icon: 'users-icon',
          roles: ['admin'],
        },
        {
          id: 'roles',
          label: '角色管理',
          path: '/admin/roles',
          icon: 'roles-icon',
          roles: ['admin'],
        },
        {
          id: 'permissions-admin',
          label: '权限管理',
          path: '/admin/permissions',
          icon: 'permissions-icon',
          roles: ['admin'],
        },
        {
          id: 'resources-admin',
          label: '资源管理',
          path: '/admin/resources',
          icon: 'resources-icon',
          roles: ['admin'],
        },
        {
          id: 'tenants-admin',
          label: '租户管理',
          path: '/admin/tenants',
          icon: 'tenants-icon',
          roles: ['admin'],
        },
      ],
    },
    {
      id: 'platform-group',
      label: '平台',
      path: '/settings',
      icon: 'settings-icon',
      roles: ['admin'],
      priority: 40,
      children: [
        {
          id: 'settings',
          label: '系统设置',
          path: '/settings',
          icon: 'settings-icon',
          roles: ['admin'],
        },
        {
          id: 'statistics',
          label: '数据统计',
          path: '/statistics',
          icon: 'stats-icon',
          roles: ['admin'],
        },
      ],
    },
    {
      id: 'profile',
      label: '个人中心',
      path: '/profile',
      icon: 'profile-icon',
      roles: ['doctor', 'consultant', 'customer', 'admin', 'operator'],
      priority: 10,
    },
  ],
};
