"""添加mcp分组server_code字段

Revision ID: 0c496d1b37a1
Revises: c2b538556d3a
Create Date: 2025-08-16 11:07:36.943377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c496d1b37a1'
down_revision: Union[str, None] = 'c2b538556d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加server_code字段
    op.add_column('mcp_tool_groups', sa.Column('server_code', sa.String(length=32), nullable=True, comment='MCP服务器代码（用于URL路径）'))
    # 创建唯一索引
    op.create_index(op.f('ix_mcp_tool_groups_server_code'), 'mcp_tool_groups', ['server_code'], unique=True)
    # 创建唯一约束
    op.create_unique_constraint('uq_mcp_groups_server_code', 'mcp_tool_groups', ['server_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除唯一约束
    op.drop_constraint('uq_mcp_groups_server_code', 'mcp_tool_groups', type_='unique')
    # 删除索引
    op.drop_index(op.f('ix_mcp_tool_groups_server_code'), table_name='mcp_tool_groups')
    # 删除字段
    op.drop_column('mcp_tool_groups', 'server_code')
    # ### end Alembic commands ###
