"""添加Dify连接配置和应用自动发现支持

Revision ID: 10be17e34d15
Revises: 1e831a74e41f
Create Date: 2025-07-10 15:30:46.822821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10be17e34d15'
down_revision: Union[str, None] = '1e831a74e41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 首先创建枚举类型
    agenttype_enum = sa.Enum('GENERAL_CHAT', 'BEAUTY_PLAN', 'CONSULTATION', 'CUSTOMER_SERVICE', 'MEDICAL_ADVICE', name='agenttype')
    agenttype_enum.create(op.get_bind())
    
    op.create_table('dify_connections',
    sa.Column('id', sa.String(length=36), nullable=False, comment='连接配置ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='连接名称'),
    sa.Column('api_base_url', sa.String(length=1024), nullable=False, comment='Dify API基础URL'),
    sa.Column('api_key', sa.Text(), nullable=False, comment='Dify API密钥'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否为活跃连接'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认连接'),
    sa.Column('description', sa.Text(), nullable=True, comment='连接描述'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True, comment='最后同步时间'),
    sa.Column('sync_status', sa.String(length=50), nullable=True, comment='同步状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Dify实例连接配置表'
    )
    op.add_column('ai_model_configs', sa.Column('dify_connection_id', sa.String(length=36), nullable=True, comment='Dify连接ID'))
    op.add_column('ai_model_configs', sa.Column('dify_app_id', sa.String(length=255), nullable=True, comment='Dify应用ID'))
    op.add_column('ai_model_configs', sa.Column('dify_app_name', sa.String(length=255), nullable=True, comment='Dify应用名称'))
    op.add_column('ai_model_configs', sa.Column('dify_app_mode', sa.String(length=50), nullable=True, comment='Dify应用模式（agent/workflow/chat）'))
    op.add_column('ai_model_configs', sa.Column('agent_type', sa.Enum('GENERAL_CHAT', 'BEAUTY_PLAN', 'CONSULTATION', 'CUSTOMER_SERVICE', 'MEDICAL_ADVICE', name='agenttype'), nullable=True, comment='Agent类型，仅Dify使用'))
    op.add_column('ai_model_configs', sa.Column('description', sa.Text(), nullable=True, comment='模型描述'))
    op.add_column('ai_model_configs', sa.Column('is_default_for_type', sa.Boolean(), nullable=True, comment='是否为该类型的默认模型'))
    op.alter_column('ai_model_configs', 'apiKey',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='API密钥（非Dify时必填）',
               existing_comment='API密钥')
    op.alter_column('ai_model_configs', 'baseUrl',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               comment='API基础URL（非Dify时必填）',
               existing_comment='API基础URL')
    op.alter_column('ai_model_configs', 'appId',
               existing_type=sa.VARCHAR(length=255),
               comment='应用ID（已废弃，使用dify_app_id）',
               existing_comment='应用ID',
               existing_nullable=True)
    op.create_foreign_key(None, 'ai_model_configs', 'dify_connections', ['dify_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_model_configs', type_='foreignkey')
    op.alter_column('ai_model_configs', 'appId',
               existing_type=sa.VARCHAR(length=255),
               comment='应用ID',
               existing_comment='应用ID（已废弃，使用dify_app_id）',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'baseUrl',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               comment='API基础URL',
               existing_comment='API基础URL（非Dify时必填）')
    op.alter_column('ai_model_configs', 'apiKey',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='API密钥',
               existing_comment='API密钥（非Dify时必填）')
    op.drop_column('ai_model_configs', 'is_default_for_type')
    op.drop_column('ai_model_configs', 'description')
    op.drop_column('ai_model_configs', 'agent_type')
    op.drop_column('ai_model_configs', 'dify_app_mode')
    op.drop_column('ai_model_configs', 'dify_app_name')
    op.drop_column('ai_model_configs', 'dify_app_id')
    op.drop_column('ai_model_configs', 'dify_connection_id')
    op.drop_table('dify_connections')
    
    # 删除枚举类型
    agenttype_enum = sa.Enum('GENERAL_CHAT', 'BEAUTY_PLAN', 'CONSULTATION', 'CUSTOMER_SERVICE', 'MEDICAL_ADVICE', name='agenttype')
    agenttype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
