"""添加顾问方案推荐相关表结构

Revision ID: 1e831a74e41f
Revises: 98ba04e7c1d8
Create Date: 2025-06-14 12:14:10.531952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e831a74e41f'
down_revision: Union[str, None] = '98ba04e7c1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
    sa.Column('id', sa.String(length=36), nullable=False, comment='模板ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='项目分类'),
    sa.Column('base_cost', sa.Float(), nullable=False, comment='基础费用'),
    sa.Column('duration', sa.String(length=50), nullable=True, comment='持续时间'),
    sa.Column('recovery_time', sa.String(length=50), nullable=True, comment='恢复时间'),
    sa.Column('expected_results', sa.Text(), nullable=True, comment='预期效果'),
    sa.Column('risks', sa.JSON(), nullable=True, comment='风险列表（JSON格式）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('suitable_age_min', sa.Integer(), nullable=True, comment='适用最小年龄'),
    sa.Column('suitable_age_max', sa.Integer(), nullable=True, comment='适用最大年龄'),
    sa.Column('suitable_concerns', sa.JSON(), nullable=True, comment='适用关注问题（JSON格式）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='项目模板表，存储标准化的医美项目模板'
    )
    op.create_table('project_types',
    sa.Column('id', sa.String(length=36), nullable=False, comment='项目类型ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目类型名称'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='项目类型显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目类型描述'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='项目参数配置（JSON格式）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='项目分类'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='项目类型表，存储医美项目类型和参数配置'
    )
    op.create_table('customer_preferences',
    sa.Column('id', sa.String(length=36), nullable=False, comment='偏好ID'),
    sa.Column('customer_id', sa.String(length=36), nullable=False, comment='客户ID'),
    sa.Column('preferred_budget_min', sa.Float(), nullable=True, comment='最小预算偏好'),
    sa.Column('preferred_budget_max', sa.Float(), nullable=True, comment='最大预算偏好'),
    sa.Column('preferred_recovery_time', sa.String(length=50), nullable=True, comment='偏好恢复时间'),
    sa.Column('preferred_project_categories', sa.JSON(), nullable=True, comment='偏好项目分类（JSON格式）'),
    sa.Column('concerns_history', sa.JSON(), nullable=True, comment='历史关注问题（JSON格式）'),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True, comment='风险承受度(low/medium/high)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    comment='客户偏好表，存储客户的个性化偏好'
    )
    op.create_table('personalized_plans',
    sa.Column('id', sa.String(length=36), nullable=False, comment='方案ID'),
    sa.Column('customer_id', sa.String(length=36), nullable=False, comment='客户ID'),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='客户姓名'),
    sa.Column('consultant_id', sa.String(length=36), nullable=False, comment='顾问ID'),
    sa.Column('consultant_name', sa.String(length=100), nullable=False, comment='顾问姓名'),
    sa.Column('customer_profile', sa.JSON(), nullable=True, comment='客户画像信息（JSON格式）'),
    sa.Column('projects', sa.JSON(), nullable=False, comment='推荐项目列表（JSON格式）'),
    sa.Column('total_cost', sa.Float(), nullable=True, comment='总费用'),
    sa.Column('estimated_timeframe', sa.String(length=100), nullable=True, comment='预计时间框架'),
    sa.Column('status', sa.Enum('DRAFT', 'SHARED', 'ACCEPTED', 'REJECTED', name='planstatusenum'), nullable=True, comment='方案状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='方案备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.user_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='个性化方案表，存储为客户定制的医美方案'
    )
    op.create_table('simulation_images',
    sa.Column('id', sa.String(length=36), nullable=False, comment='模拟图像ID'),
    sa.Column('customer_id', sa.String(length=36), nullable=False, comment='客户ID'),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='客户姓名'),
    sa.Column('original_image_path', sa.String(length=500), nullable=False, comment='原始图像路径'),
    sa.Column('simulated_image_path', sa.String(length=500), nullable=False, comment='模拟图像路径'),
    sa.Column('project_type_id', sa.String(length=36), nullable=False, comment='项目类型ID'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='模拟参数（JSON格式）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('consultant_id', sa.String(length=36), nullable=False, comment='顾问ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.user_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.user_id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='术前模拟图像表，存储客户的模拟图像'
    )
    op.create_table('plan_versions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('plan_id', sa.String(length=36), nullable=False, comment='方案ID'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('projects', sa.JSON(), nullable=False, comment='项目列表快照（JSON格式）'),
    sa.Column('total_cost', sa.Float(), nullable=False, comment='总费用快照'),
    sa.Column('notes', sa.Text(), nullable=True, comment='版本备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['personalized_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='方案版本表，存储方案的历史版本'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_versions')
    op.drop_table('simulation_images')
    op.drop_table('personalized_plans')
    op.drop_table('customer_preferences')
    op.drop_table('project_types')
    op.drop_table('project_templates')
    # ### end Alembic commands ###
