"""add model provider

Revision ID: 212988cadf17
Revises: 52bca11a42c3
Create Date: 2025-05-19 19:27:33.066711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '212988cadf17'
down_revision: Union[str, None] = '52bca11a42c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 第1步：添加可为空的provider列
    op.add_column('ai_model_configs', sa.Column('provider', sa.String(length=255), nullable=True))
    # 第2步：更新所有已有记录，设置默认值'openai'
    op.execute(text("UPDATE ai_model_configs SET provider = 'openai'"))
    # 第3步：设置非空约束
    op.alter_column('ai_model_configs', 'provider', nullable=False)
    
    # 直接添加appId列(可为空)
    op.add_column('ai_model_configs', sa.Column('appId', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_model_configs', 'appId')
    op.drop_column('ai_model_configs', 'provider')
    # ### end Alembic commands ###
