"""移除database_config字段，回归微服务架构原则

Revision ID: 27fca9bcdf63
Revises: 2e56243f8328
Create Date: 2025-07-11 09:23:18.207061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fca9bcdf63'
down_revision: Union[str, None] = '2e56243f8328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
