"""添加Dify数据库配置字段支持直连获取应用列表

Revision ID: 2e56243f8328
Revises: f494ba7907b1
Create Date: 2025-07-11 08:20:25.193444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e56243f8328'
down_revision: Union[str, None] = 'f494ba7907b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'admin_level',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_comment='管理员级别',
               existing_nullable=True)
    op.add_column('dify_connections', sa.Column('database_config', sa.JSON(), nullable=True, comment='Dify数据库连接配置（JSON格式）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dify_connections', 'database_config')
    op.alter_column('administrators', 'admin_level',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'basic'::character varying"),
               existing_comment='管理员级别',
               existing_nullable=True)
    # ### end Alembic commands ###
