"""添加个人中心相关表：用户偏好设置、默认角色、登录历史

Revision ID: 2eb7c7caa1bb
Revises: 9bcd30067a3d
Create Date: 2025-07-16 23:22:36.406485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb7c7caa1bb'
down_revision: Union[str, None] = '9bcd30067a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建用户偏好设置表
    op.create_table(
        'user_preferences',
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
        sa.Column('notification_enabled', sa.Boolean(), nullable=False, comment='是否启用通知'),
        sa.Column('email_notification', sa.Boolean(), nullable=False, comment='是否启用邮件通知'),
        sa.Column('push_notification', sa.Boolean(), nullable=False, comment='是否启用推送通知'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
        comment='用户偏好设置表，存储用户个性化偏好'
    )
    
    # 创建用户默认角色设置表
    op.create_table(
        'user_default_roles',
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
        sa.Column('default_role', sa.String(length=50), nullable=False, comment='默认角色名称'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
        comment='用户默认角色设置表，存储用户首次登录的默认角色'
    )
    
    # 创建登录历史表
    op.create_table(
        'login_history',
        sa.Column('id', sa.String(length=36), nullable=False, comment='登录记录ID'),
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
        sa.Column('ip_address', sa.String(length=45), nullable=True, comment='登录IP地址'),
        sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理信息'),
        sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='登录时间'),
        sa.Column('login_role', sa.String(length=50), nullable=True, comment='登录时使用的角色'),
        sa.Column('location', sa.String(length=100), nullable=True, comment='登录地点'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='登录历史表，记录用户登录信息'
    )
    
    # 创建索引
    op.create_index('idx_login_history_user_id', 'login_history', ['user_id'], unique=False)
    op.create_index('idx_login_history_login_time', 'login_history', ['login_time'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index('idx_login_history_login_time', table_name='login_history')
    op.drop_index('idx_login_history_user_id', table_name='login_history')
    
    # 删除表（按相反顺序）
    op.drop_table('login_history')
    op.drop_table('user_default_roles')
    op.drop_table('user_preferences')
    
    # ### end Alembic commands ###
