"""Add consultation_type and summary to Conversation, remove consultation_history from CustomerProfile

Revision ID: 31df4dacd6e4
Revises: 
Create Date: 2025-05-26 07:40:57.945797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31df4dacd6e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('consultation_type', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_column('customer_profiles', 'consultation_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('consultation_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'summary')
    op.drop_column('conversations', 'consultation_type')
    # ### end Alembic commands ###
