"""migrate_to_uuid

Revision ID: 3eb5f3eb2986
Revises: 212988cadf17
Create Date: 2025-05-21 19:32:04.235339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb5f3eb2986'
down_revision: Union[str, None] = '212988cadf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('administrators', 'admin_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('administrators', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_administrators_id', table_name='administrators')
    op.add_column('ai_model_configs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('ai_model_configs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('ai_model_configs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'maxTokens',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'system_settings_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index('ix_ai_model_configs_id', table_name='ai_model_configs')
    op.alter_column('consultants', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('consultants', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_consultants_id', table_name='consultants')
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('customer_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('customers', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('customers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_customers_id', table_name='customers')
    op.alter_column('doctors', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('doctors', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_doctors_id', table_name='doctors')
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('operators', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('operators', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_operators_id', table_name='operators')
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_roles_id', table_name='roles')
    op.add_column('system_settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('system_settings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('system_settings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_system_settings_id', table_name='system_settings')
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               server_default=sa.text("nextval('users_id_seq'::regclass)"),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_system_settings_id', 'system_settings', ['id'], unique=False)
    op.alter_column('system_settings', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('system_settings', 'updated_at')
    op.drop_column('system_settings', 'created_at')
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.alter_column('roles', 'id',
               existing_type=sa.String(length=36),
               server_default=sa.text("nextval('roles_id_seq'::regclass)"),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_operators_id', 'operators', ['id'], unique=False)
    op.alter_column('operators', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('operators', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.create_index('ix_doctors_id', 'doctors', ['id'], unique=False)
    op.alter_column('doctors', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('doctors', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.alter_column('customers', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customers', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_profiles', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_consultants_id', 'consultants', ['id'], unique=False)
    op.alter_column('consultants', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('consultants', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_ai_model_configs_id', 'ai_model_configs', ['id'], unique=False)
    op.alter_column('ai_model_configs', 'system_settings_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'maxTokens',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('ai_model_configs', 'updated_at')
    op.drop_column('ai_model_configs', 'created_at')
    op.create_index('ix_administrators_id', 'administrators', ['id'], unique=False)
    op.alter_column('administrators', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('administrators', 'admin_level',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('administrators', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
