"""field deleted

Revision ID: 52bca11a42c3
Revises: 719fe9f5395e
Create Date: 2025-05-19 16:11:53.393595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bca11a42c3'
down_revision: Union[str, None] = '719fe9f5395e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'themeColor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('themeColor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
