"""自动迁移:模型更新

Revision ID: 541d6686490c
Revises: 31df4dacd6e4
Create Date: 2025-05-28 16:57:50.965753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '541d6686490c'
down_revision: Union[str, None] = '31df4dacd6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('administrators', 'admin_level',
               existing_type=sa.VARCHAR(),
               comment='管理员级别',
               existing_nullable=True)
    op.alter_column('administrators', 'access_permissions',
               existing_type=sa.TEXT(),
               comment='权限描述',
               existing_nullable=True)
    op.create_table_comment(
        'administrators',
        '系统管理员表，存储管理员扩展信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('ai_model_configs', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='模型配置ID',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'modelName',
               existing_type=sa.VARCHAR(length=255),
               comment='模型名称',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'apiKey',
               existing_type=sa.TEXT(),
               comment='API密钥',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'baseUrl',
               existing_type=sa.VARCHAR(length=1024),
               comment='API基础URL',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'maxTokens',
               existing_type=sa.VARCHAR(),
               comment='最大Token数',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='采样温度',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'provider',
               existing_type=sa.VARCHAR(length=255),
               comment='服务商',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'appId',
               existing_type=sa.VARCHAR(length=255),
               comment='应用ID',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'system_settings_id',
               existing_type=sa.VARCHAR(length=36),
               comment='系统设置ID',
               existing_nullable=True)
    op.create_table_comment(
        'ai_model_configs',
        'AI模型配置表，存储AI模型相关配置',
        existing_comment=None,
        schema=None
    )
    op.alter_column('consultants', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('consultants', 'expertise',
               existing_type=sa.VARCHAR(),
               comment='专长领域',
               existing_nullable=True)
    op.alter_column('consultants', 'performance_metrics',
               existing_type=sa.TEXT(),
               comment='业绩指标',
               existing_nullable=True)
    op.create_table_comment(
        'consultants',
        '医美顾问表，存储顾问扩展信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('conversations', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(),
               comment='会话标题',
               existing_nullable=False)
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               comment='顾客用户ID',
               existing_nullable=False)
    op.alter_column('conversations', 'assigned_consultant_id',
               existing_type=sa.VARCHAR(length=36),
               comment='分配的顾问用户ID',
               existing_nullable=True)
    op.alter_column('conversations', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='会话是否激活',
               existing_nullable=True)
    op.alter_column('conversations', 'consultation_type',
               existing_type=sa.VARCHAR(),
               comment='咨询类型',
               existing_nullable=True)
    op.alter_column('conversations', 'summary',
               existing_type=sa.TEXT(),
               comment='会话总结',
               existing_nullable=True)
    op.create_table_comment(
        'conversations',
        '聊天会话表，存储用户与顾问的会话信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('customer_profiles', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='档案ID',
               existing_nullable=False)
    op.alter_column('customer_profiles', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               comment='顾客用户ID',
               existing_nullable=False)
    op.alter_column('customer_profiles', 'medical_history',
               existing_type=sa.TEXT(),
               comment='病史',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'allergies',
               existing_type=sa.TEXT(),
               comment='过敏史（JSON字符串）',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'preferences',
               existing_type=sa.TEXT(),
               comment='偏好',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'tags',
               existing_type=sa.TEXT(),
               comment='标签（JSON字符串）',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'risk_notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='风险提示信息',
               existing_nullable=True)
    op.create_table_comment(
        'customer_profiles',
        '客户档案表，扩展客户详细信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('customers', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('customers', 'medical_history',
               existing_type=sa.TEXT(),
               comment='病史',
               existing_nullable=True)
    op.alter_column('customers', 'allergies',
               existing_type=sa.TEXT(),
               comment='过敏史',
               existing_nullable=True)
    op.alter_column('customers', 'preferences',
               existing_type=sa.TEXT(),
               comment='偏好',
               existing_nullable=True)
    op.create_table_comment(
        'customers',
        '顾客表，存储顾客扩展信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('doctors', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               comment='专科方向',
               existing_nullable=True)
    op.alter_column('doctors', 'certification',
               existing_type=sa.VARCHAR(),
               comment='资格证书',
               existing_nullable=True)
    op.alter_column('doctors', 'license_number',
               existing_type=sa.VARCHAR(),
               comment='执业证号',
               existing_nullable=True)
    op.create_table_comment(
        'doctors',
        '医生表，存储医生扩展信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='消息ID',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(length=36),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('text', 'image', 'voice', 'file', 'system', name='message_type'),
               comment='消息类型',
               existing_nullable=True)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.VARCHAR(length=36),
               comment='发送者用户ID',
               existing_nullable=False)
    op.alter_column('messages', 'sender_type',
               existing_type=postgresql.ENUM('customer', 'consultant', 'doctor', 'ai', 'system', name='sender_type'),
               comment='发送者类型',
               existing_nullable=False)
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='是否已读',
               existing_nullable=True)
    op.alter_column('messages', 'is_important',
               existing_type=sa.BOOLEAN(),
               comment='是否重要',
               existing_nullable=True)
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='消息时间戳',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'messages',
        '聊天消息表，存储会话中的消息内容',
        existing_comment=None,
        schema=None
    )
    op.alter_column('operators', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('operators', 'department',
               existing_type=sa.VARCHAR(),
               comment='所属部门',
               existing_nullable=True)
    op.alter_column('operators', 'responsibilities',
               existing_type=sa.TEXT(),
               comment='职责描述',
               existing_nullable=True)
    op.create_table_comment(
        'operators',
        '运营人员表，存储机构运营人员扩展信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('roles', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='角色ID',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               comment='角色名称',
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(),
               comment='角色描述',
               existing_nullable=True)
    op.create_table_comment(
        'roles',
        '角色表，存储系统所有角色信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('system_settings', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='系统设置ID',
               existing_nullable=False)
    op.alter_column('system_settings', 'siteName',
               existing_type=sa.VARCHAR(length=255),
               comment='站点名称',
               existing_nullable=False)
    op.alter_column('system_settings', 'logoUrl',
               existing_type=sa.VARCHAR(length=1024),
               comment='站点Logo URL',
               existing_nullable=True)
    op.alter_column('system_settings', 'defaultModelId',
               existing_type=sa.VARCHAR(length=255),
               comment='默认AI模型ID',
               existing_nullable=True)
    op.alter_column('system_settings', 'maintenanceMode',
               existing_type=sa.BOOLEAN(),
               comment='维护模式开关',
               existing_nullable=True)
    op.alter_column('system_settings', 'userRegistrationEnabled',
               existing_type=sa.BOOLEAN(),
               comment='是否允许用户注册',
               existing_nullable=True)
    op.create_table_comment(
        'system_settings',
        '系统设置表，存储全局系统配置',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.VARCHAR(length=36),
               comment='角色ID',
               existing_nullable=False)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='分配时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='邮箱',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='加密密码',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=True)
    op.create_table_comment(
        'users',
        '用户表，存储所有用户基础信息',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='用户表，存储所有用户基础信息',
        schema=None
    )
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='加密密码',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='分配时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='角色ID',
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_table_comment(
        'system_settings',
        existing_comment='系统设置表，存储全局系统配置',
        schema=None
    )
    op.alter_column('system_settings', 'userRegistrationEnabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否允许用户注册',
               existing_nullable=True)
    op.alter_column('system_settings', 'maintenanceMode',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='维护模式开关',
               existing_nullable=True)
    op.alter_column('system_settings', 'defaultModelId',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='默认AI模型ID',
               existing_nullable=True)
    op.alter_column('system_settings', 'logoUrl',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='站点Logo URL',
               existing_nullable=True)
    op.alter_column('system_settings', 'siteName',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='站点名称',
               existing_nullable=False)
    op.alter_column('system_settings', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='系统设置ID',
               existing_nullable=False)
    op.drop_table_comment(
        'roles',
        existing_comment='角色表，存储系统所有角色信息',
        schema=None
    )
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='角色描述',
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='角色ID',
               existing_nullable=False)
    op.drop_table_comment(
        'operators',
        existing_comment='运营人员表，存储机构运营人员扩展信息',
        schema=None
    )
    op.alter_column('operators', 'responsibilities',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='职责描述',
               existing_nullable=True)
    op.alter_column('operators', 'department',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='所属部门',
               existing_nullable=True)
    op.alter_column('operators', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_table_comment(
        'messages',
        existing_comment='聊天消息表，存储会话中的消息内容',
        schema=None
    )
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='消息时间戳',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'is_important',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否重要',
               existing_nullable=True)
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已读',
               existing_nullable=True)
    op.alter_column('messages', 'sender_type',
               existing_type=postgresql.ENUM('customer', 'consultant', 'doctor', 'ai', 'system', name='sender_type'),
               comment=None,
               existing_comment='发送者类型',
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='发送者用户ID',
               existing_nullable=False)
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('text', 'image', 'voice', 'file', 'system', name='message_type'),
               comment=None,
               existing_comment='消息类型',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='消息ID',
               existing_nullable=False)
    op.drop_table_comment(
        'doctors',
        existing_comment='医生表，存储医生扩展信息',
        schema=None
    )
    op.alter_column('doctors', 'license_number',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='执业证号',
               existing_nullable=True)
    op.alter_column('doctors', 'certification',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='资格证书',
               existing_nullable=True)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='专科方向',
               existing_nullable=True)
    op.alter_column('doctors', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_table_comment(
        'customers',
        existing_comment='顾客表，存储顾客扩展信息',
        schema=None
    )
    op.alter_column('customers', 'preferences',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='偏好',
               existing_nullable=True)
    op.alter_column('customers', 'allergies',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='过敏史',
               existing_nullable=True)
    op.alter_column('customers', 'medical_history',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='病史',
               existing_nullable=True)
    op.alter_column('customers', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_table_comment(
        'customer_profiles',
        existing_comment='客户档案表，扩展客户详细信息',
        schema=None
    )
    op.alter_column('customer_profiles', 'risk_notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='风险提示信息',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'tags',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='标签（JSON字符串）',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'preferences',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='偏好',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'allergies',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='过敏史（JSON字符串）',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'medical_history',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='病史',
               existing_nullable=True)
    op.alter_column('customer_profiles', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='顾客用户ID',
               existing_nullable=False)
    op.alter_column('customer_profiles', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='档案ID',
               existing_nullable=False)
    op.drop_table_comment(
        'conversations',
        existing_comment='聊天会话表，存储用户与顾问的会话信息',
        schema=None
    )
    op.alter_column('conversations', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='会话总结',
               existing_nullable=True)
    op.alter_column('conversations', 'consultation_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='咨询类型',
               existing_nullable=True)
    op.alter_column('conversations', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='会话是否激活',
               existing_nullable=True)
    op.alter_column('conversations', 'assigned_consultant_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='分配的顾问用户ID',
               existing_nullable=True)
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='顾客用户ID',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='会话标题',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.drop_table_comment(
        'consultants',
        existing_comment='医美顾问表，存储顾问扩展信息',
        schema=None
    )
    op.alter_column('consultants', 'performance_metrics',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='业绩指标',
               existing_nullable=True)
    op.alter_column('consultants', 'expertise',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='专长领域',
               existing_nullable=True)
    op.alter_column('consultants', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_table_comment(
        'ai_model_configs',
        existing_comment='AI模型配置表，存储AI模型相关配置',
        schema=None
    )
    op.alter_column('ai_model_configs', 'system_settings_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='系统设置ID',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'appId',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='应用ID',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'provider',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='服务商',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='采样温度',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'maxTokens',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='最大Token数',
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'baseUrl',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='API基础URL',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'apiKey',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='API密钥',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'modelName',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=False)
    op.alter_column('ai_model_configs', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='模型配置ID',
               existing_nullable=False)
    op.drop_table_comment(
        'administrators',
        existing_comment='系统管理员表，存储管理员扩展信息',
        schema=None
    )
    op.alter_column('administrators', 'access_permissions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='权限描述',
               existing_nullable=True)
    op.alter_column('administrators', 'admin_level',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='管理员级别',
               existing_nullable=True)
    op.alter_column('administrators', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    # ### end Alembic commands ###
