"""add field

Revision ID: 7ef009f6cf7e
Revises: 541d6686490c
Create Date: 2025-05-29 06:15:57.484531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef009f6cf7e'
down_revision: Union[str, None] = '541d6686490c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_ai_controlled', sa.Boolean(), nullable=True, comment='当前会话是否由AI控制（True=AI，False=顾问接管）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_ai_controlled')
    # ### end Alembic commands ###
