"""修复profile表结构添加id主键

Revision ID: 848ce2a2d9bf
Revises: 2eb7c7caa1bb
Create Date: 2025-07-17 23:19:01.188378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848ce2a2d9bf'
down_revision: Union[str, None] = '2eb7c7caa1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_login_history_login_time', table_name='login_history')
    op.drop_index('idx_login_history_user_id', table_name='login_history')
    
    # 处理 user_default_roles 表
    # 先删除现有主键约束
    op.drop_constraint('user_default_roles_pkey', 'user_default_roles', type_='primary')
    # 添加 id 列
    op.add_column('user_default_roles', sa.Column('id', sa.String(length=36), nullable=True, comment='记录ID'))
    # 为现有数据填充 UUID
    op.execute("UPDATE user_default_roles SET id = gen_random_uuid() WHERE id IS NULL")
    # 设置为非空并作为主键
    op.alter_column('user_default_roles', 'id', nullable=False)
    op.create_primary_key(None, 'user_default_roles', ['id'])
    # 为 user_id 添加唯一约束
    op.create_unique_constraint(None, 'user_default_roles', ['user_id'])
    
    # 处理 user_preferences 表
    # 先删除现有主键约束
    op.drop_constraint('user_preferences_pkey', 'user_preferences', type_='primary')
    # 添加 id 列
    op.add_column('user_preferences', sa.Column('id', sa.String(length=36), nullable=True, comment='偏好设置ID'))
    # 为现有数据填充 UUID
    op.execute("UPDATE user_preferences SET id = gen_random_uuid() WHERE id IS NULL")
    # 设置为非空并作为主键
    op.alter_column('user_preferences', 'id', nullable=False)
    op.create_primary_key(None, 'user_preferences', ['id'])
    # 为 user_id 添加唯一约束
    op.create_unique_constraint(None, 'user_preferences', ['user_id'])
    op.create_table_comment(
        'user_preferences',
        '用户偏好设置表，存储用户个性化配置',
        existing_comment='用户偏好设置表，存储用户个性化偏好',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_preferences',
        '用户偏好设置表，存储用户个性化偏好',
        existing_comment='用户偏好设置表，存储用户个性化配置',
        schema=None
    )
    # 删除 user_preferences 上 user_id 的唯一约束
    op.drop_constraint('user_preferences_user_id_key', 'user_preferences', type_='unique')
    op.drop_column('user_preferences', 'id')
    # 删除 user_default_roles 上 user_id 的唯一约束
    op.drop_constraint('user_default_roles_user_id_key', 'user_default_roles', type_='unique')
    op.drop_column('user_default_roles', 'id')
    op.create_index('idx_login_history_user_id', 'login_history', ['user_id'], unique=False)
    op.create_index('idx_login_history_login_time', 'login_history', ['login_time'], unique=False)
    # ### end Alembic commands ###
