"""refactor_customer_profile_insights

Revision ID: 884721983323
Revises: 76f686c16c95
Create Date: 2026-01-13 16:14:22.894698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '884721983323'
down_revision: Union[str, None] = '76f686c16c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create customer_insights table
    op.create_table('customer_insights',
    sa.Column('id', sa.String(length=36), nullable=False, comment='洞察ID'),
    sa.Column('profile_id', sa.String(length=36), nullable=False, comment='关联档案ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='维度分类(预算/需求/偏好等)'),
    sa.Column('content', sa.Text(), nullable=False, comment='洞察内容/事实描述'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='来源(AI/人工)'),
    sa.Column('created_by_name', sa.String(length=100), nullable=True, comment='创建人姓名(如果是人工录入)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态(active/archived)'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度(0.0-1.0)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='修改人ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='客户动态画像/洞察表'
    )

    # 2. Update customer_profiles table
    op.add_column('customer_profiles', sa.Column('life_cycle_stage', sa.String(length=50), nullable=True, comment='生命周期阶段(lead/prospect/deal/customer)'))
    op.add_column('customer_profiles', sa.Column('industry', sa.String(length=100), nullable=True, comment='所属行业'))
    op.add_column('customer_profiles', sa.Column('company_scale', sa.String(length=50), nullable=True, comment='公司规模'))
    op.add_column('customer_profiles', sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI生成的客户全景摘要'))
    op.add_column('customer_profiles', sa.Column('extra_data', sa.JSON(), nullable=True, comment='扩展属性'))
    
    op.create_table_comment(
        'customer_profiles',
        '客户核心档案表，存储结构化销售状态',
        existing_comment='客户档案表，扩展客户详细信息',
        schema=None
    )
    
    op.drop_column('customer_profiles', 'tags')
    op.drop_column('customer_profiles', 'risk_notes')
    op.drop_column('customer_profiles', 'preferences')
    op.drop_column('customer_profiles', 'allergies')
    op.drop_column('customer_profiles', 'medical_history')

    # 3. Update customers table
    op.drop_column('customers', 'medical_history')
    op.drop_column('customers', 'allergies')
    op.drop_column('customers', 'preferences')

    # NOTE: The rest of the autogenerated changes are unrelated to this task and caused errors.
    # They are commented out to focus on the customer profile refactor.
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert customers table
    op.add_column('customers', sa.Column('preferences', sa.TEXT(), autoincrement=False, nullable=True, comment='偏好'))
    op.add_column('customers', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True, comment='过敏史'))
    op.add_column('customers', sa.Column('medical_history', sa.TEXT(), autoincrement=False, nullable=True, comment='病史'))
    
    # Revert customer_profiles table
    op.add_column('customer_profiles', sa.Column('medical_history', sa.TEXT(), autoincrement=False, nullable=True, comment='病史'))
    op.add_column('customer_profiles', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True, comment='过敏史（JSON字符串）'))
    op.add_column('customer_profiles', sa.Column('preferences', sa.TEXT(), autoincrement=False, nullable=True, comment='偏好'))
    op.add_column('customer_profiles', sa.Column('risk_notes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='风险提示信息'))
    op.add_column('customer_profiles', sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True, comment='标签（JSON字符串）'))
    
    op.create_table_comment(
        'customer_profiles',
        '客户档案表，扩展客户详细信息',
        existing_comment='客户核心档案表，存储结构化销售状态',
        schema=None
    )
    
    op.drop_column('customer_profiles', 'extra_data')
    op.drop_column('customer_profiles', 'ai_summary')
    op.drop_column('customer_profiles', 'company_scale')
    op.drop_column('customer_profiles', 'industry')
    op.drop_column('customer_profiles', 'life_cycle_stage')
    
    # Drop customer_insights table
    op.drop_table('customer_insights')
    
    # ### end Alembic commands ###
