"""添加dify动态配置表

Revision ID: 9bcd30067a3d
Revises: 9a3b312e93df
Create Date: 2025-07-15 23:26:10.570474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcd30067a3d'
down_revision: Union[str, None] = '9a3b312e93df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dify_configs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Dify配置ID'),
    sa.Column('config_name', sa.String(length=255), nullable=False, comment='配置名称'),
    sa.Column('base_url', sa.String(length=1024), nullable=False, comment='Dify API基础URL'),
    sa.Column('chat_app_id', sa.String(length=255), nullable=True, comment='聊天应用ID'),
    sa.Column('chat_api_key', sa.Text(), nullable=True, comment='聊天应用API密钥（加密存储）'),
    sa.Column('beauty_app_id', sa.String(length=255), nullable=True, comment='医美方案专家应用ID'),
    sa.Column('beauty_api_key', sa.Text(), nullable=True, comment='医美方案专家API密钥（加密存储）'),
    sa.Column('summary_app_id', sa.String(length=255), nullable=True, comment='咨询总结工作流应用ID'),
    sa.Column('summary_api_key', sa.Text(), nullable=True, comment='咨询总结工作流API密钥（加密存储）'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='请求超时时间（秒）'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Dify配置表，存储Dify应用配置'
    )
    op.create_index('idx_dify_config_enabled', 'dify_configs', ['enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dify_config_enabled', table_name='dify_configs')
    op.drop_table('dify_configs')
    # ### end Alembic commands ###
