"""add extra_metadata to conversations table

Revision ID: aa1eb668317b
Revises: 07ce9993a478
Create Date: 2025-10-01 17:16:57.610009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1eb668317b'
down_revision: Union[str, None] = '07ce9993a478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='附加元数据'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'extra_metadata')
    # ### end Alembic commands ###
