"""add table

Revision ID: b77c4f6589f7
Revises: fb93a0d72d28
Create Date: 2025-06-08 22:49:56.225115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77c4f6589f7'
down_revision: Union[str, None] = 'fb93a0d72d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('upload_id', sa.String(length=64), nullable=False, comment='上传ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件总大小（字节）'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分片大小（字节）'),
    sa.Column('total_chunks', sa.Integer(), nullable=False, comment='总分片数'),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='关联会话ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='上传用户ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='上传状态: uploading, completed, failed, cancelled'),
    sa.Column('final_object_name', sa.String(length=500), nullable=True, comment='合并后的文件对象名'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_upload_id'), 'upload_sessions', ['upload_id'], unique=True)
    op.create_table('upload_chunks',
    sa.Column('upload_id', sa.String(length=64), nullable=False, comment='关联上传ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分片索引（从0开始）'),
    sa.Column('object_name', sa.String(length=500), nullable=False, comment='分片在MinIO中的对象名'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分片实际大小（字节）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='分片状态: uploading, completed, failed'),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='分片校验和（可选）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'chunk_index', name='uk_upload_chunk_index'),
    comment='上传分片表，记录每个分片的上传状态和存储位置'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_chunks')
    op.drop_index(op.f('ix_upload_sessions_upload_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
