"""optimize_user_and_permission_models

Revision ID: f0cdaaa0406e
Revises: merge_heads_cln1
Create Date: 2025-11-23 10:50:00.885837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0cdaaa0406e'
down_revision: Union[str, None] = 'merge_heads_cln1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'access_permissions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_comment='权限描述',
               existing_nullable=True,
               postgresql_using='access_permissions::json')
    op.alter_column('consultants', 'performance_metrics',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_comment='业绩指标',
               existing_nullable=True,
               postgresql_using='performance_metrics::json')

    # Permission model changes
    op.add_column('permissions', sa.Column('code', sa.String(length=100), nullable=False, comment='权限标识码，如 user:create'))
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_column('permissions', 'resource')
    op.drop_column('permissions', 'action')

    # User model changes
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index('ix_users_phone', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint('uq_user_email_tenant', 'users', ['email', 'tenant_id'])
    op.create_unique_constraint('uq_user_username_tenant', 'users', ['username', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username_tenant', 'users', type_='unique')
    op.drop_constraint('uq_user_email_tenant', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    
    op.add_column('permissions', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='权限动作'))
    op.add_column('permissions', sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='权限资源'))
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_column('permissions', 'code')

    op.alter_column('consultants', 'performance_metrics',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_comment='业绩指标',
               existing_nullable=True)
    op.alter_column('administrators', 'access_permissions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_comment='权限描述',
               existing_nullable=True)
    # ### end Alembic commands ###
