"""添加断点续传支持的upload表

Revision ID: fb93a0d72d28
Revises: 7ef009f6cf7e
Create Date: 2025-06-08 19:54:43.878682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb93a0d72d28'
down_revision: Union[str, None] = '7ef009f6cf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
